/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-28 09:51:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("jar:file:/E:/webbanmatkinh/webbanmatkinh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webbanmatkinh/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1634219349198L));
    _jspx_dependants.put("jar:file:/E:/webbanmatkinh/webbanmatkinh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webbanmatkinh/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar", Long.valueOf(1631692614158L));
    _jspx_dependants.put("jar:file:/E:/webbanmatkinh/webbanmatkinh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webbanmatkinh/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511752906000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1630531027718L));
    _jspx_dependants.put("jar:file:/E:/webbanmatkinh/webbanmatkinh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webbanmatkinh/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/E:/webbanmatkinh/webbanmatkinh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webbanmatkinh/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1437576592000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1630531020626L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1629538926692L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"pre-loader\">\r\n");
      out.write("		<div class=\"pre-loader-box\">\r\n");
      out.write("			<div class=\"loader-logo\"><img src=\"vendors/images/deskapp-logo.svg\" alt=\"\"></div>\r\n");
      out.write("			<div class='loader-progress' id=\"progress_div\">\r\n");
      out.write("				<div class='bar' id='bar1'></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class='percent' id='percent1'>0%</div>\r\n");
      out.write("			<div class=\"loading-text\">\r\n");
      out.write("				Loading...\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<div class=\"header-left\">\r\n");
      out.write("			<div class=\"menu-icon dw dw-menu\"></div>\r\n");
      out.write("			<div class=\"search-toggle-icon dw dw-search2\" data-toggle=\"header_search\"></div>\r\n");
      out.write("			<div class=\"header-search\">\r\n");
      out.write("				<form>\r\n");
      out.write("					<div class=\"form-group mb-0\">\r\n");
      out.write("						<i class=\"dw dw-search2 search-icon\"></i>\r\n");
      out.write("						<input type=\"text\" class=\"form-control search-input\" placeholder=\"Search Here\">\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<a class=\"dropdown-toggle no-arrow\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ion-arrow-down-c\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("							<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("								<div class=\"form-group row\">\r\n");
      out.write("									<label class=\"col-sm-12 col-md-2 col-form-label\">From</label>\r\n");
      out.write("									<div class=\"col-sm-12 col-md-10\">\r\n");
      out.write("										<input class=\"form-control form-control-sm form-control-line\" type=\"text\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group row\">\r\n");
      out.write("									<label class=\"col-sm-12 col-md-2 col-form-label\">To</label>\r\n");
      out.write("									<div class=\"col-sm-12 col-md-10\">\r\n");
      out.write("										<input class=\"form-control form-control-sm form-control-line\" type=\"text\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group row\">\r\n");
      out.write("									<label class=\"col-sm-12 col-md-2 col-form-label\">Subject</label>\r\n");
      out.write("									<div class=\"col-sm-12 col-md-10\">\r\n");
      out.write("										<input class=\"form-control form-control-sm form-control-line\" type=\"text\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"text-right\">\r\n");
      out.write("									<button class=\"btn btn-primary\">Search</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-right\">\r\n");
      out.write("			<div class=\"dashboard-setting user-notification\">\r\n");
      out.write("				<div class=\"dropdown\">\r\n");
      out.write("					<a class=\"dropdown-toggle no-arrow\" href=\"javascript:;\" data-toggle=\"right-sidebar\">\r\n");
      out.write("						<i class=\"dw dw-settings2\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"user-notification\">\r\n");
      out.write("				<div class=\"dropdown\">\r\n");
      out.write("					<a class=\"dropdown-toggle no-arrow\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("						<i class=\"icon-copy dw dw-notification\"></i>\r\n");
      out.write("						<span class=\"badge notification-active\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("						<div class=\"notification-list mx-h-350 customscroll\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">\r\n");
      out.write("										<img src=\"vendors/images/img.jpg\" alt=\"\">\r\n");
      out.write("										<h3>John Doe</h3>\r\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">\r\n");
      out.write("										<img src=\"vendors/images/photo1.jpg\" alt=\"\">\r\n");
      out.write("										<h3>Lea R. Frith</h3>\r\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">\r\n");
      out.write("										<img src=\"vendors/images/photo2.jpg\" alt=\"\">\r\n");
      out.write("										<h3>Erik L. Richards</h3>\r\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">\r\n");
      out.write("										<img src=\"vendors/images/photo3.jpg\" alt=\"\">\r\n");
      out.write("										<h3>John Doe</h3>\r\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">\r\n");
      out.write("										<img src=\"vendors/images/photo4.jpg\" alt=\"\">\r\n");
      out.write("										<h3>Renee I. Hansen</h3>\r\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<a href=\"#\">\r\n");
      out.write("										<img src=\"vendors/images/img.jpg\" alt=\"\">\r\n");
      out.write("										<h3>Vicki M. Coleman</h3>\r\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"user-info-dropdown\">\r\n");
      out.write("				<div class=\"dropdown\">\r\n");
      out.write("					<a class=\"dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("						<span class=\"user-icon\">\r\n");
      out.write("							<img src=\"vendors/images/photo1.jpg\" alt=\"\">\r\n");
      out.write("						</span>\r\n");
      out.write("						<span class=\"user-name\">Ross C. Lopez</span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"dropdown-menu dropdown-menu-right dropdown-menu-icon-list\">\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"profile.html\"><i class=\"dw dw-user1\"></i> Profile</a>\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"profile.html\"><i class=\"dw dw-settings2\"></i> Setting</a>\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"faq.html\"><i class=\"dw dw-help\"></i> Help</a>\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"login.html\"><i class=\"dw dw-logout\"></i> Log Out</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"github-link\">\r\n");
      out.write("				<a href=\"https://github.com/dropways/deskapp\" target=\"_blank\"><img src=\"vendors/images/github.svg\" alt=\"\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"right-sidebar\">\r\n");
      out.write("		<div class=\"sidebar-title\">\r\n");
      out.write("			<h3 class=\"weight-600 font-16 text-blue\">\r\n");
      out.write("				Layout Settings\r\n");
      out.write("				<span class=\"btn-block font-weight-400 font-12\">User Interface Settings</span>\r\n");
      out.write("			</h3>\r\n");
      out.write("			<div class=\"close-sidebar\" data-toggle=\"right-sidebar-close\">\r\n");
      out.write("				<i class=\"icon-copy ion-close-round\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"right-sidebar-body customscroll\">\r\n");
      out.write("			<div class=\"right-sidebar-body-content\">\r\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Header Background</h4>\r\n");
      out.write("				<div class=\"sidebar-btn-group pb-30 mb-10\">\r\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary header-white active\">White</a>\r\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary header-dark\">Dark</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Sidebar Background</h4>\r\n");
      out.write("				<div class=\"sidebar-btn-group pb-30 mb-10\">\r\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary sidebar-light \">White</a>\r\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary sidebar-dark active\">Dark</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Menu Dropdown Icon</h4>\r\n");
      out.write("				<div class=\"sidebar-radio-group pb-10 mb-10\">\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebaricon-1\" name=\"menu-dropdown-icon\" class=\"custom-control-input\" value=\"icon-style-1\" checked=\"\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebaricon-1\"><i class=\"fa fa-angle-down\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebaricon-2\" name=\"menu-dropdown-icon\" class=\"custom-control-input\" value=\"icon-style-2\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebaricon-2\"><i class=\"ion-plus-round\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebaricon-3\" name=\"menu-dropdown-icon\" class=\"custom-control-input\" value=\"icon-style-3\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebaricon-3\"><i class=\"fa fa-angle-double-right\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Menu List Icon</h4>\r\n");
      out.write("				<div class=\"sidebar-radio-group pb-30 mb-10\">\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-1\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-1\" checked=\"\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-1\"><i class=\"ion-minus-round\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-2\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-2\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-2\"><i class=\"fa fa-circle-o\" aria-hidden=\"true\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-3\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-3\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-3\"><i class=\"dw dw-check\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-4\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-4\" checked=\"\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-4\"><i class=\"icon-copy dw dw-next-2\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-5\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-5\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-5\"><i class=\"dw dw-fast-forward-1\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-6\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-6\">\r\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-6\"><i class=\"dw dw-next\"></i></label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"reset-options pt-30 text-center\">\r\n");
      out.write("					<button class=\"btn btn-danger\" id=\"reset-settings\">Reset Settings</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"left-side-bar\">\r\n");
      out.write("		<div class=\"brand-logo\">\r\n");
      out.write("			<a href=\"index.html\">\r\n");
      out.write("				<img src=\"vendors/images/deskapp-logo.svg\" alt=\"\" class=\"dark-logo\">\r\n");
      out.write("				<img src=\"vendors/images/deskapp-logo-white.svg\" alt=\"\" class=\"light-logo\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<div class=\"close-sidebar\" data-toggle=\"left-sidebar-close\">\r\n");
      out.write("				<i class=\"ion-close-round\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"menu-block customscroll\">\r\n");
      out.write("			<div class=\"sidebar-menu\">\r\n");
      out.write("				<ul id=\"accordion-menu\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle no-arrow\">\r\n");
      out.write("							<span class=\"micon dw dw-house-1\"></span><span class=\"mtext\">Home</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"dropdown\">\r\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\r\n");
      out.write("							<span class=\"micon dw dw-edit2\"></span><span class=\"mtext\">Forms</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<ul class=\"submenu\">\r\n");
      out.write("							<li><a href=\"form-basic.html\">Form Basic</a></li>\r\n");
      out.write("							<li><a href=\"form-wizard.html\">Form Wizard</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"dropdown\">\r\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\r\n");
      out.write("							<span class=\"micon dw dw-library\"></span><span class=\"mtext\">Tables</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<ul class=\"submenu\">\r\n");
      out.write("							<li><a href=\"datatable.html\">DataTables</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					<li class=\"dropdown\">\r\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\r\n");
      out.write("							<span class=\"micon dw dw-right-arrow1\"></span><span class=\"mtext\">Additional Pages</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<ul class=\"submenu\">\r\n");
      out.write("							<li><a href=\"login.html\">Login</a></li>\r\n");
      out.write("							<li><a href=\"forgot-password.html\">Forgot Password</a></li>\r\n");
      out.write("							<li><a href=\"reset-password.html\">Reset Password</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"dropdown\">\r\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\r\n");
      out.write("							<span class=\"micon dw dw-copy\"></span><span class=\"mtext\">Extra Pages</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<ul class=\"submenu\">\r\n");
      out.write("							<li><a href=\"blank.html\">Blank</a></li>\r\n");
      out.write("							<li><a href=\"contact-directory.html\">Contact Directory</a></li>\r\n");
      out.write("							<li><a href=\"blog.html\">Blog</a></li>\r\n");
      out.write("							<li><a href=\"blog-detail.html\">Blog Detail</a></li>\r\n");
      out.write("							<li><a href=\"product.html\">Product</a></li>\r\n");
      out.write("							<li><a href=\"product-detail.html\">Product Detail</a></li>\r\n");
      out.write("							<li><a href=\"faq.html\">FAQ</a></li>\r\n");
      out.write("							<li><a href=\"profile.html\">Profile</a></li>\r\n");
      out.write("							<li><a href=\"gallery.html\">Gallery</a></li>\r\n");
      out.write("							<li><a href=\"pricing-table.html\">Pricing Tables</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"invoice.html\" class=\"dropdown-toggle no-arrow\">\r\n");
      out.write("							<span class=\"micon dw dw-invoice\"></span><span class=\"mtext\">Invoice</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"dropdown-divider\"></div>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"mobile-menu-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"main-container\">\r\n");
      out.write("		<div class=\"pd-ltr-20\">\r\n");
      out.write("			<div class=\"card-box pd-20 height-100-p mb-30\">\r\n");
      out.write("				<div class=\"row align-items-center\">\r\n");
      out.write("					<div class=\"col-md-4\">\r\n");
      out.write("						<img src=\"vendors/images/banner-img.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-8\">\r\n");
      out.write("						<h4 class=\"font-20 weight-500 mb-10 text-capitalize\">\r\n");
      out.write("							Welcome back <div class=\"weight-600 font-30 text-blue\">Johnny Brown!</div>\r\n");
      out.write("						</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"card-box mb-30\">\r\n");
      out.write("				<h2 class=\"h4 pd-20\">Best Selling Products</h2>\r\n");
      out.write("				<table class=\"data-table table nowrap\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th class=\"table-plus datatable-nosort\">Product</th>\r\n");
      out.write("							<th>Name</th>\r\n");
      out.write("							<th>Color</th>\r\n");
      out.write("							<th>Size</th>\r\n");
      out.write("							<th>Price</th>\r\n");
      out.write("							<th>Oty</th>\r\n");
      out.write("							<th class=\"datatable-nosort\">Action</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"table-plus\">\r\n");
      out.write("								<img src=\"vendors/images/product-1.jpg\" width=\"70\" height=\"70\" alt=\"\">\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<h5 class=\"font-16\">Shirt</h5>\r\n");
      out.write("								by John Doe\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>Black</td>\r\n");
      out.write("							<td>M</td>\r\n");
      out.write("							<td>$1000</td>\r\n");
      out.write("							<td>1</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<div class=\"dropdown\">\r\n");
      out.write("									<a class=\"btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("										<i class=\"dw dw-more\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									<div class=\"dropdown-menu dropdown-menu-right dropdown-menu-icon-list\">\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-eye\"></i> View</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-edit2\"></i> Edit</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-delete-3\"></i> Delete</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"table-plus\">\r\n");
      out.write("								<img src=\"vendors/images/product-2.jpg\" width=\"70\" height=\"70\" alt=\"\">\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<h5 class=\"font-16\">Boots</h5>\r\n");
      out.write("								by Lea R. Frith\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>brown</td>\r\n");
      out.write("							<td>9UK</td>\r\n");
      out.write("							<td>$900</td>\r\n");
      out.write("							<td>1</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<div class=\"dropdown\">\r\n");
      out.write("									<a class=\"btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("										<i class=\"dw dw-more\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									<div class=\"dropdown-menu dropdown-menu-right dropdown-menu-icon-list\">\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-eye\"></i> View</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-edit2\"></i> Edit</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-delete-3\"></i> Delete</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"table-plus\">\r\n");
      out.write("								<img src=\"vendors/images/product-3.jpg\" width=\"70\" height=\"70\" alt=\"\">\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<h5 class=\"font-16\">Hat</h5>\r\n");
      out.write("								by Erik L. Richards\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>Orange</td>\r\n");
      out.write("							<td>M</td>\r\n");
      out.write("							<td>$100</td>\r\n");
      out.write("							<td>4</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<div class=\"dropdown\">\r\n");
      out.write("									<a class=\"btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("										<i class=\"dw dw-more\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									<div class=\"dropdown-menu dropdown-menu-right dropdown-menu-icon-list\">\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-eye\"></i> View</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-edit2\"></i> Edit</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-delete-3\"></i> Delete</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"table-plus\">\r\n");
      out.write("								<img src=\"vendors/images/product-4.jpg\" width=\"70\" height=\"70\" alt=\"\">\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<h5 class=\"font-16\">Long Dress</h5>\r\n");
      out.write("								by Renee I. Hansen\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>Gray</td>\r\n");
      out.write("							<td>L</td>\r\n");
      out.write("							<td>$1000</td>\r\n");
      out.write("							<td>1</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<div class=\"dropdown\">\r\n");
      out.write("									<a class=\"btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("										<i class=\"dw dw-more\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									<div class=\"dropdown-menu dropdown-menu-right dropdown-menu-icon-list\">\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-eye\"></i> View</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-edit2\"></i> Edit</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-delete-3\"></i> Delete</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"table-plus\">\r\n");
      out.write("								<img src=\"vendors/images/product-5.jpg\" width=\"70\" height=\"70\" alt=\"\">\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<h5 class=\"font-16\">Blazer</h5>\r\n");
      out.write("								by Vicki M. Coleman\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>Blue</td>\r\n");
      out.write("							<td>M</td>\r\n");
      out.write("							<td>$1000</td>\r\n");
      out.write("							<td>1</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<div class=\"dropdown\">\r\n");
      out.write("									<a class=\"btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("										<i class=\"dw dw-more\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									<div class=\"dropdown-menu dropdown-menu-right dropdown-menu-icon-list\">\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-eye\"></i> View</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-edit2\"></i> Edit</a>\r\n");
      out.write("										<a class=\"dropdown-item\" href=\"#\"><i class=\"dw dw-delete-3\"></i> Delete</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- js -->\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
